_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -98.4375
  - 30.6001
  - 2
description: just the entire world, dude
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 2
minzoom: 0
name: world countries
source: "tmsource:///Volumes/HDD/stephan/Documents/tilehut/tutorial/countries-boundaries.tm2source"
styles: 
  - style.mss
template: ''
